FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:build as build

RUN install_packages curl wget build-essential libelf-dev awscli bc flex libssl-dev
COPY . /usr/src/app
WORKDIR /usr/src/app

ARG VERSION

RUN echo $VERSION
RUN ./build.sh %%RESIN_MACHINE_NAME%% $VERSION example_module


FROM balenalib/%%BALENA_MACHINE_NAME%%-debian

COPY --from=build /usr/src/app /usr/src/app
WORKDIR /usr/src/app

CMD ./run.sh
